name: Terraform Apply

inputs:
  tf-workspace:
    required: true
    description: "The Terraform Cloud workspace to use for this apply."
  config-directory:
    required: false
    default: "./"
    description: "The path to the Terraform configuration directory."

runs:
    using: composite
    steps:
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@bff80f5420b44028d4a0cca9a7b77846d35ddc17 # v1.3.2
        id: apply-upload
        with:
          workspace: ${{ inputs.tf-workspace }}
          directory: ${{ inputs.config-directory }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@bff80f5420b44028d4a0cca9a7b77846d35ddc17 # v1.3.2
        id: apply-run
        with:
          workspace: ${{ inputs.tf-workspace }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@bff80f5420b44028d4a0cca9a7b77846d35ddc17 # v1.3.2
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"