name: Assume AWS Role
description: Assume an AWS Role in the specified AWS account.
inputs:
  aws-region:
    required: false
    default: eu-west-1
    description: "The AWS region to use."
  aws-account-id:
    required: true
    description: "The AWS account ID to assume the role in."
  role-name:
    required: true
    description: "The name of the role to assume."


runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b #v6.2.0
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.role-name }}
        aws-region: ${{ inputs.aws-region }}