on:
  push:
    branches: [main]
    paths-ignore:
      - "wena-tests/**"
      - "wena-terraform/identity/**"

permissions:
  contents: read
  id-token: write

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  deploy:
    name: Wena infrastructure deployment to ${{ matrix.environment }} environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]

    environment: ${{ matrix.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v 6.0.2

    - name: Assume Github OIDC Role
      uses: ./.github/actions/assume-aws-role
      with:
        aws-account-id: ${{ vars.AWS_IDENTITY_ACCOUNT_ID }}
        role-name: "@GithubOidc"

    - name: Terraform Plan
      uses: ./.github/actions/terraform-plan
      with:
        tf-workspace: ${{ vars.TF_WORKSPACE }}

    - name: Terraform Apply
      uses: ./.github/actions/terraform-apply
      with:
        tf-workspace: ${{ vars.TF_WORKSPACE }}

  