on: 
    pull_request:
        types: [opened, synchronize, reopened, labeled]
        paths:
            - 'wena-terraform/identity/**'

permissions:
  contents: read
  pull-requests: write
  
env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  HUSKY: 0

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: identity

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v 6.0.2
    
    - name: Terraform Plan
      uses: ./.github/actions/terraform-plan
      with:
        config-directory: wena-terraform/identity
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
