on:
  push:
    branches: [main]
    paths:
      - "wena-terraform/identity/**"

permissions:
  contents: read

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  deploy:
    name: Wena Identity infrastructure deployment
    runs-on: ubuntu-latest

    environment: identity

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Terraform Plan
      uses: ./.github/actions/terraform-plan
      with:
        config-directory: wena-terraform/identity

    - name: Terraform Apply
      uses: ./.github/actions/terraform-apply
      with:
        config-directory: wena-terraform/identity

  