on:
  push:
    branches: [main]
    paths:
      - "wena-terraform/identity/**"

permissions:
  # so GitHub can check out this repo using the default github.token
  contents: read

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  deploy:
    name: Wena Identity infrastructure deployment
    runs-on: ubuntu-latest

    environment: identity

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Terraform Plan
      uses: ./.github/actions/terraform-plan
      with:
        tf-workspace: ${{ vars.TF_WORKSPACE }}

    - name: Terraform Apply
      uses: ./.github/actions/terraform-apply
      with:
        tf-workspace: ${{ vars.TF_WORKSPACE }}

  