name: ci cd

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  wena_e2e_tests:
    name: "E2e tests"
    uses: mrience/wena/.github/workflows/wena-e2e-tests.yaml@feature-003/setup-github-actions

  publish_wena_test_runner:
    runs-on: ubuntu-latest
    needs: [wena_e2e_tests]
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build Typescript
      uses: ./.github/actions/build
    - name: Publish npm package
      run: |
        echo "@mrience:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        cd wena-framework
        npm publish
      env:
        NODE_AUTH_TOKEN: ยง${{secrets.GITHUB_TOKEN}}
