name: ci

on:
  workflow_dispatch:

jobs:
  ci: 
    defaults:
      run:
        working-directory: ./wena-framework
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --workspaces true

    - run: npm run build

    - run: cd wena-test-runner

    - run: npm link

    - run: ../wena-tests

    - run: npm ci

    - run: wena-test-runner
