name: ci

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Build Typescript
      uses: ./.github/actions/build

    - run: |
        cd wena-framework/packages/wena-test-runner
        npm link
    - name: Publish npm package
      run: |
        cd wena-framework
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}