name: ci

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/build

    - run: |
        #!/bin/bash
        if [ -e ./wena-framework/packages/wena-test-runner/dist/bin.js ]
        then
          echo "ok"
        else
          echo "nok"
        fi

    - run: |
        cd wena-framework/packages/wena-test-runner
        npm link

    - run: |
        cd wena-tests
        npm ci
        npm link wena-test-runner
        wena-test-runner

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
