name: framework ci cd

on:
  push:
    branches: [ main ]
    paths: wena-framework/**
  workflow_dispatch:

jobs:
  wena_e2e_tests:
    name: "E2e tests"
    uses: mrience/wena/.github/workflows/wena-e2e-tests.yaml@main

  publish_wena_test_runner:
    runs-on: ubuntu-latest
    needs: [wena_e2e_tests]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Build Typescript
      uses: ./.github/actions/build

    - name: Publish npm package
      run: |
        cd wena-framework
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
